Name: Product
Host: 0.0.0.0
Port: 8888

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

ProductRpc:
  Etcd:
    Hosts:
      - 192.168.88.128:2379
    Key: product.rpc

Telemetry:
  Name: product.api
  Endpoint: http://192.168.88.128:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

Prometheus:
  Host: 192.168.88.128
  Port: 9081
  Path: /metrics